--[[
,-----.                 ,--.        ,------.         ,--.         
|  |) /_ ,--.--. ,--,--.`--',--,--, |  .--. ' ,--,--.`--',--,--,  
|  .-.  \|  .--'' ,-.  |,--.|      \|  '--' |' ,-.  |,--.|      \ 
|  '--' /|  |   \ '-'  ||  ||  ||  ||  | --' \ '-'  ||  ||  ||  | 
`------' `--'    `--`--'`--'`--''--'`--'      `--`--'`--'`--''--' 

             ,. -,                         _  °         , ·. ,.-·~·.,   ‘    
by     ,.·'´,    ,'\         ,.·,       :´¨   ;\         /  ·'´,.-·-.,   `,'‚    
   ,·'´ .·´'´-·'´::::\'     ,'   ,'\     .'´ ,·´::'\       /  .'´\:::::::'\   '\ °  
  ;    ';:::\::\::;:'      ;'  ,'::\ .·' .·´::::::;'   ,·'  ,'::::\:;:-·-:';  ';\‚  
  \·.    `·;:'-·'´         ;  ;::·´ .·´:::::::;·´   ;.   ';:::;´       ,'  ,':'\‚   discord.gg/myTvmbfJMR
   \:`·.   '`·,  '        ';  '´   ;´::::::;·´        ';   ;::;       ,'´ .'´\::';‚
     `·:'`·,   \'         ;  ;'\   '\::;·´            ';   ':;:   ,.·´,.·´::::\;'°
      ,.'-:;'  ,·\       ;  ;:\:'·.  '·., ,.·';'        \·,   `*´,.·'´::::::;·´   
 ,·'´     ,.·´:::'\      ;_;::'\::`·._,.·'´:\'         \\:¯::\:::::::;:·´      
  \`*'´\::::::::;·'‘     \::'\:;' '·::\::\:::::'\         `\:::::\;::·'´  °       
   \::::\:;:·´           '\::\     `·'\::\;:·'´'             ¯                  
     '`*'´‘                 ¯          ¯'                   ‘                  
description:
Works only in popular games, like KAT (if script doesnt works, check logs [F9])
 - Game-detect
 - No ui
]]-- BrainPain
local notifLib = loadstring(game:HttpGet(('https://gist.githubusercontent.com/lokk1y-dev/adbd2be45ba69c4ce71a39bcb4b8899a/raw/c1041fd9cff9b4e1ae5fdf619ef6582592d1a6f4/notifLib.lua'),true))()
rconsoleclear()
rconsolename("BRAIN PAIN")
rconsoleprint("@@LIGHT_RED@@")
rconsoleprint("Brain")
rconsoleprint("Pain")
rconsoleprint("@@WHITE@@")
rconsoleprint("\nBy ")
rconsoleprint("@@LIGHT_BLUE@@")
rconsoleprint("sKo\ndiscord.gg/myTvmbfJMR")
rconsoleprint("@@WHITE@@")
rconsoleprint("\n\n")
rconsoleprint("@@RED@@")
local notifLib = loadstring(game:HttpGet(('https://gist.githubusercontent.com/lokk1y-dev/adbd2be45ba69c4ce71a39bcb4b8899a/raw/c1041fd9cff9b4e1ae5fdf619ef6582592d1a6f4/notifLib.lua'),true))()
if game.PlaceId == 621129760 then
    loadstring(game:HttpGet(('https://gist.githubusercontent.com/lokk1y-dev/c1aa44d2cafdb0777f158bbf7cc43032/raw/21778340dfb10ade27d794dc873fd596ae24e0f3/owlHub.lua'),true))()
    rconsoleprint("@@WHITE@@")
    notifLib.prompt('BrainPain', 'Executed!', 5)
    rconsolename("BRAIN PAIN - KAT")
    rconsoleprint("\nGame")
    rconsoleprint("@@YELLOW@@")
    rconsoleprint(" KAT")
    rconsoleprint("@@WHITE@@")
    rconsoleprint(" founded")
elseif game.PlaceId == 12109643 then 
    notifLib.prompt('BrainPain', 'Hi', 5)
    rconsolename("BRAIN PAIN - Fencing")
    rconsoleprint("\nGame")
    rconsoleprint("@@YELLOW@@")
    rconsoleprint(" Fencing")
    rconsoleprint("@@WHITE@@")
    rconsoleprint(" founded")
elseif game.PlaceId == 292439477 then
    loadstring(game:HttpGet("https://ducksite.xyz/ceri/main.lua"))()
    rconsoleprint("@@WHITE@@")
    notifLib.prompt('BrainPain', 'Executed!', 5)
    rconsolename("BRAIN PAIN - Phantom Forces")
    rconsoleprint("\nGame")
    rconsoleprint("@@YELLOW@@")
    rconsoleprint(" Phantom Forces")
    rconsoleprint("@@WHITE@@")
    rconsoleprint(" founded")
elseif game.PlaceId == 606849621 then
    loadstring(game:HttpGet("https://darkhub.xyz/remote-script.lua", true))()
    rconsoleclear()
    rconsolename("BRAIN PAIN")
    rconsoleprint("@@LIGHT_RED@@")
    rconsoleprint("Brain")
    rconsoleprint("Pain")
    rconsoleprint("@@WHITE@@")
    rconsoleprint("\nBy ")
    rconsoleprint("@@LIGHT_BLUE@@")
    rconsoleprint("sKo\ndiscord.gg/myTvmbfJMR")
    rconsoleprint("@@WHITE@@")
    rconsoleprint("\n\n")
    rconsoleprint("@@RED@@")
    rconsoleprint("@@WHITE@@")
    notifLib.prompt('BrainPain', 'Executed!', 5)
    rconsolename("BRAIN PAIN - Jailbreak")
    rconsoleprint("\nGame")
    rconsoleprint("@@YELLOW@@")
    rconsoleprint(" Jailbreak")
    rconsoleprint("@@WHITE@@")
    rconsoleprint(" founded")
elseif game.PlaceId == 3233893879 then -- Bad Business
    loadstring(game:HttpGet("https://raw.githubusercontent.com/WetCheezit/BadHaxx/main/Script.lua"))()
    rconsoleprint("@@WHITE@@")
    notifLib.prompt('BrainPain', 'Executed!', 5)
    rconsolename("BRAIN PAIN - Bad Business")
    rconsoleprint("\nGame")
    rconsoleprint("@@YELLOW@@")
    rconsoleprint(" Bad Business")
    rconsoleprint("@@WHITE@@")
    rconsoleprint(" founded")
elseif game.PlaceId == 2317712696 then
    loadstring(game:HttpGet('https://raw.githubusercontent.com/1201for/littlegui/main/The-Wild-One'))()
    rconsoleprint("@@WHITE@@")
    notifLib.prompt('BrainPain', 'Executed!', 5)
    rconsolename("BRAIN PAIN - The Wild West")
    rconsoleprint("\nGame")
    rconsoleprint("@@YELLOW@@")
    rconsoleprint(" Wild West")
    rconsoleprint("@@WHITE@@")
    rconsoleprint(" founded")
elseif game.PlaceId == 2882332175 then
    loadstring(game:HttpGet("https://paste.c-net.org/OrientedArise",true))()
    rconsoleprint("@@WHITE@@")
    notifLib.prompt('BrainPain', 'Executed!', 5)
    rconsolename("BRAIN PAIN - Be dead forever simulator")
    rconsoleprint("\nGame")
    rconsoleprint("@@YELLOW@@")
    rconsoleprint(" Be dead forever simulator")
    rconsoleprint("@@WHITE@@")
    rconsoleprint(" founded")
    notifLib.prompt('BrainPain', 'Now its real brainpain\nFind commands in source code', 7)
elseif game.PlaceId == 2377868063 then
    loadstring(game:HttpGet("https://darkhub.xyz/remote-script.lua", true))()
    rconsoleclear()
    rconsolename("BRAIN PAIN")
    rconsoleprint("@@LIGHT_RED@@")
    rconsoleprint("Brain")
    rconsoleprint("Pain")
    rconsoleprint("@@WHITE@@")
    rconsoleprint("By ")
    rconsoleprint("@@LIGHT_BLUE@@")
    rconsoleprint("sKo\ndiscord.gg/myTvmbfJMR")
    rconsoleprint("@@WHITE@@")
    rconsoleprint("\n")
    rconsoleprint("@@RED@@")
    rconsoleprint("@@WHITE@@")
    notifLib.prompt('BrainPain', 'Executed!', 5)
    rconsolename("BRAIN PAIN - Strucid")
    rconsoleprint("\nGame")
    rconsoleprint("@@YELLOW@@")
    rconsoleprint(" Strucid")
    rconsoleprint("@@WHITE@@")
    rconsoleprint(" founded")
elseif game.PlaceId == 7791873535 then
    loadstring(game:HttpGet("https://darkhub.xyz/remote-script.lua", true))()
    rconsoleclear()
    rconsolename("BRAIN PAIN")
    rconsoleprint("@@LIGHT_RED@@")
    rconsoleprint("Brain")
    rconsoleprint("Pain")
    rconsoleprint("@@WHITE@@")
    rconsoleprint("\nBy ")
    rconsoleprint("@@LIGHT_BLUE@@")
    rconsoleprint("sKo\ndiscord.gg/myTvmbfJMR")
    rconsoleprint("@@WHITE@@")
    rconsoleprint("\n")
    rconsoleprint("@@RED@@")
    rconsoleprint("@@WHITE@@")
    notifLib.prompt('BrainPain', 'Executed!', 5)
    rconsolename("BRAIN PAIN - Realistic Hood")
    rconsoleprint("\nGame")
    rconsoleprint("@@YELLOW@@")
    rconsoleprint(" Realistic Hood")
    rconsoleprint("@@WHITE@@")
    rconsoleprint(" founded")
elseif game.PlaceId == 3461767162 then
    loadstring(game:HttpGet("https://darkhub.xyz/remote-script.lua", true))()
    rconsoleclear()
    rconsolename("BRAIN PAIN")
    rconsoleprint("@@LIGHT_RED@@")
    rconsoleprint("Brain")
    rconsoleprint("Pain")
    rconsoleprint("@@WHITE@@")
    rconsoleprint("\nBy ")
    rconsoleprint("@@LIGHT_BLUE@@")
    rconsoleprint("sKo\ndiscord.gg/myTvmbfJMR")
    rconsoleprint("@@WHITE@@")
    rconsoleprint("\n")
    rconsoleprint("@@RED@@")
    rconsoleprint("@@WHITE@@")
    notifLib.prompt('BrainPain', 'Executed!', 5)
    rconsolename("BRAIN PAIN - Runker 51")
    rconsoleprint("\nGame")
    rconsoleprint("@@YELLOW@@")
    rconsoleprint(" Runker 51")
    rconsoleprint("@@WHITE@@")
    rconsoleprint(" founded")
elseif game.PlaceId == 301549746 then
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Pawel12d/hexagon/main/scripts/CounterBlox.lua', true))()
    rconsoleprint("@@WHITE@@")
    notifLib.prompt('BrainPain', 'Executed!', 5)
    rconsolename("BRAIN PAIN - Counter Blox")
    rconsoleprint("\nGame")
    rconsoleprint("@@YELLOW@@")
    rconsoleprint(" Counter Blox")
    rconsoleprint("@@WHITE@@")
    rconsoleprint(" founded")
elseif game.PlaceId == 286090429 then
    loadstring(game:HttpGet("https://darkhub.xyz/remote-script.lua", true))()
    rconsoleclear()
    rconsolename("BRAIN PAIN")
    rconsoleprint("@@LIGHT_RED@@")
    rconsoleprint("Brain")
    rconsoleprint("Pain")
    rconsoleprint("@@WHITE@@")
    rconsoleprint("By ")
    rconsoleprint("@@LIGHT_BLUE@@")
    rconsoleprint("sKo\ndiscord.gg/myTvmbfJMR")
    rconsoleprint("@@WHITE@@")
    rconsoleprint("\n")
    rconsoleprint("@@RED@@")
    rconsoleprint("@@WHITE@@")
    notifLib.prompt('BrainPain', 'Executed!', 5)
    rconsolename("BRAIN PAIN - Arsenal")
    rconsoleprint("\nGame")
    rconsoleprint("@@YELLOW@@")
    rconsoleprint(" Arsenal")
    rconsoleprint("@@WHITE@@")
    rconsoleprint(" founded")
else
    print("Use brainpain in: KAT, Phantom Forces, Jailbreak, Bad Business, The Wild West, Be dead forever simulator, Strucid, Realistic Hood Runker 51, Counter Blox and Arsenal")
    notifLib.prompt('BrainPain', 'No games founded, check console [F9]', 5)
    rconsolename("BRAIN PAIN - NoGamesFounded")
    rconsoleprint("\n\nNo Games Founded\n\nUse brainpain in: KAT, Phantom Forces, Jailbreak, Bad Business, The Wild West, Be dead forever simulator, Strucid, Realistic Hood Runker 51, Counter Blox and Arsenal")
    rconsoleprint("@@WHITE@@")
end